### ISSUE TITLE
EMC unity need configure Agent?

### ISSUE THREAD

**Issue by len-666** [aklyuk/zabbix-emc-unity#13]
Hi aklyuk, thanks for your scripts. I have an iusse about this step:  In agent configuration file, /etc/zabbix/zabbix_agentd.conf must be set parameter ServerActive=xxx.xxx.xxx.xxx   .     ---> It means the EMC unity also install zabbix agent ?    I contact vendor ,I cann't upload any files to EMC server.         Appreciate you can give me some suggestion. Thanks a lot.

**Comment by rlrobs** [comment]
Try this:

1 - Import templates
2 - Put on script unity_get_state.py in ExternalScripts in zabbix server.
ps: Search the line ExternalScripts in zabbix_server.conf

3 - chown zabbix:zabbix unity_get_state.py

**Comment by aklyuk** [comment]
Hi.
Script is executing on zabbix-proxy on my side. 
ServerActive parameter in /etc/zabbix/zabbix_agentd.conf  is an destination, where i can transfer traps.
I didn't want to create script parameter for that.

NO, it not need to install zabbiz-agent to unity.  It is impossible, likely.

**Comment by len-666** [comment]
> Try this:
> 
> 1 - Import templates
> 2 - Put on script unity_get_state.py in ExternalScripts in zabbix server.
> ps: Search the line ExternalScripts in zabbix_server.conf
> 
> 3 - chown zabbix:zabbix unity_get_state.py

**Comment by len-666** [comment]
> Hi.
> Script is executing on zabbix-proxy on my side.
> ServerActive parameter in /etc/zabbix/zabbix_agentd.conf is an destination, where i can transfer traps.
> I didn't want to create script parameter for that.
> 
> NO, it not need to install zabbiz-agent to unity. It is impossible, likely.




Thanks for your suggestion.  
I have an issue is that how does the zabbix server  know the EMC unity  ip?  The Macros seems don't  include api-ip .    I need great the  api-ip  Macros ?

Thanks!

**Comment by len-666** [comment]
> Hi.
> Script is executing on zabbix-proxy on my side.
> ServerActive parameter in /etc/zabbix/zabbix_agentd.conf is an destination, where i can transfer traps.
> I didn't want to create script parameter for that.
> 
> NO, it not need to install zabbiz-agent to unity. It is impossible, likely.

Thanks for your reply?  I only have an zabbix server to monitor Unity.  Could you  introduce how does the zabbix  server know the Unity server ip.  It seems the Macros dont  define the unity ip.

**Comment by aklyuk** [comment]
Hi.
On zabbix-server host  need install zabbix-agent. In file /etc/zabbix/zabbix-agentd.conf, parameter ServerActive must be set address zabbix-server host.

**Comment by len-666** [comment]
> 
> 
> Hi.
> On zabbix-server host need install zabbix-agent. In file /etc/zabbix/zabbix-agentd.conf, parameter ServerActive must be set address zabbix-server host.


Yes, I set the ServerActive server ip =127.0.0.1 as the agent  and  zabbix server are installed in same server .
Script return value 0 after configure the the [commands(--discovery  and --status).

I create a host and set the agent  ip 127.0.0.1 
But the Monitoring--latest data is will don't change periodically .  The date  dont't change periodically . The last check time is old time . 


![host ](https://user-images.githubusercontent.com/52193146/97421167-2770ac00-1947-11eb-8b4a-6978d2ca4478.png)
![latest date ](https://user-images.githubusercontent.com/52193146/97421176-29d30600-1947-11eb-9120-e370f28cec97.png)

Also I don't know how the zabbix server know the EMC unirty ip ?

It seems the py script don't know the EMC ip . It connect 127.0.0.1 , not  Emc IP .
/tmp/unity_state.log :


2020-10-28 17:51:55,393 - unity_logger - ERROR - Connection Error Occurs: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /api/types/loginSessionInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f97ea7b24a8>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by aklyuk** [comment]
on zabbix web interface,  host interfaces must be set unity address
![unity_properties](https://user-images.githubusercontent.com/30729388/97422471-e369b100-191e-11eb-8bc4-74266f956ef2.png)

**Comment by len-666** [comment]
Thank you very much ,aklyuk. It is working now ! It confused me one month. Thanks again.

**Comment by len-666** [comment]
Also thank you rlrobs.
