### ISSUE TITLE
the script execute fail

### ISSUE THREAD

**Issue by ghost1988** [aklyuk/zabbix-emc-unity#2]
Hi :

     i  test unity_get_state.py on emc unity 400,it can not work,please help,thanks.

2019-10-16 14:17:41,017 - unity_logger - ERROR - Connection Return Code = 401

**Comment by ghost1988** [comment]
Hi :
   I try it again,it still can not work.

2019-10-16 18:09:37,306 - unity_logger - ERROR - Connection Return Code = 401

**Comment by idcsvr** [comment]
[root@infrazabbix zabbix-emc-unity]# ./unity_get_state.py --api_ip=10.224.19.21 --api_port=443 --api_user=admin --api_password='*****' --storage_name="***-unity550f" --discovery
Traceback (most recent call last):
  File "./unity_get_state.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by kirov-qh** [comment]
> [root@infrazabbix zabbix-emc-unity]# ./unity_get_state.py --api_ip=10.224.19.21 --api_port=443 --api_user=admin --api_password='**_**' --storage_name="**_-unity550f" --discovery
> Traceback (most recent call last):
> File "./unity_get_state.py", line 12, in
> import requests
> ModuleNotFoundError: No module named 'requests'
> 
> ########
> 
> Hi , could you please help on this issue ?

You did not install the requests library. Use the following method to install:

**Comment by kirov-qh** [comment]
> [root@infrazabbix zabbix-emc-unity]# ./unity_get_state.py --api_ip=10.224.19.21 --api_port=443 --api_user=admin --api_password='**_**' --storage_name="**_-unity550f" --discovery
> Traceback (most recent call last):
> File "./unity_get_state.py", line 12, in
> import requests
> ModuleNotFoundError: No module named 'requests'
> 
> ########
> 
> Hi , could you please help on this issue ?

You did not install the requests library. Use the following method to install:
# pip install requests

**Comment by kirov-qh** [comment]
> [root@infrazabbix zabbix-emc-unity]# ./unity_get_state.py --api_ip=10.224.19.21 --api_port=443 --api_user=admin --api_password='**_**' --storage_name="**_-unity550f" --discovery
> Traceback (most recent call last):
> File "./unity_get_state.py", line 12, in
> import requests
> ModuleNotFoundError: No module named 'requests'
> 
> ########
> 
> Hi , could you please help on this issue ?

You did not install the requests library. Use the following method to install:
[root@infrazabbix zabbix-emc-unity]# pip install requests
