### ISSUE TITLE
What does it mean to return code 2？

### ISSUE THREAD

**Issue by taizi19881227** [aklyuk/zabbix-emc-unity#6]
Hi
Unity400，Execute your script to return code 2, the "get health state" item and "get discovery" item collected is 2.
The log indicates that the login was successful, I can't collect the automatically discovered monitoring items.
./unity_get_state.py --api_ip=xxx.xxx.xxx.xxx --api_port=443 --api_user=username_on_storagedevice --api_password='password' --storage_name="storage-name_in_zabbix" --discovery
return code 2
Can you help me?
Regards

**Comment by Vinikober** [comment]
Same return here.

**Comment by taizi19881227** [comment]
I've solved it.
create host: The value of "Host name" is EMC's storage_name
