### ISSUE TITLE
Automatic Execution Script

### ISSUE THREAD

**Issue by csperansa** [aklyuk/zabbix-emc-unity#8]
Hi All!

I was configured the external script on the zabbix proxy and the command was executed successfull.
My question is about: How to execute automatic script on the zabbix for colect data?

If I execute the manaul command of the script, the data is sent from zabbix proxy to zabbix server, but doesn´t work the automatic execution to colect data from EMC Unity.

What´s happen?

**Comment by aklyuk** [comment]
What permission has unity_get_state.py and unity_state.log?

**Comment by csperansa** [comment]
Hi!

Sorry for my mistake.

When i copied the code and saved the file, i didin't see a error in the block of the Sender that i needed to alter.

I delayed to look the problem and solve the same.

Now the Zabbix server is receiving the data from script that he execute in Zabbix Proxy.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by csperansa** [comment]
The problem was the code when I copied to server and edited for custom parameters.
