### ISSUE TITLE
return code 1000

### ISSUE THREAD

**Issue by jbollman7** [aklyuk/zabbix-emc-unity#9]
Hello, First let me say thanks for the code.

On the first step, you have this for the instructions

    In Linux-console on zabbix-server or zabbix-proxy need run this command to make discovery. Script must return value 0 in case of success.

`./unity_get_state.py --api_ip=xxx.xxx.xxx.xxx --api_port=443 --api_user=username_on_storagedevice --api_password='password' --storage_name="storage-name_in_zabbix" --discovery`

Assumptions: API-ip parameter wants the storage device IP.
api_user and api_password are the creds for the storage device(unity)

Im stuck on storage_name parameter. I gave it the name of whats listed on the unity 'dc1vsa01' 
In your above example you mentioned storage name in zabbix?  I just stood up a zabbix test intance to see how the code works, so i dont have anything in zabbix.  Can you please explained what i am missing?

Thank you!!

**Comment by aklyuk** [comment]
hello. 
"storage-name_in_zabbix"  -  is host name of storage in zabbix web interface. It may be  "test_storage" or "unity600-01"

**Comment by jbollman7** [comment]
`./unity_get_state.py --api_ip=10.171.87.70 --api_port=443 --api_user=admin --api_password=Unity123! --storage_name=VIRT29132R5N2G --discovery`
1000

I then tweaked the password, and i got error code 60. I do think this time im communicating with the unity. Are there logs to check why i'am getting return code 1000 instead of 0?

Thanks!

**Comment by jbollman7** [comment]
I added some print statements to see where the code was bombing out.  Exception on line 206 is being called.
I also `print(oops)`
output was 'entries'

Any help would be greatly appreciated, thank you
